[package]
name = "action"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { workspace = true }
tokio = { workspace = true }
core = { path = "../core" }
theming = { path = "../theming" }

