[package]
name = "command"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
strelka_core = { path = "../core" }
futures = { version = "0.3" }
