[package]
name = "strelka_core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
crossbeam-channel = { workspace = true }
tracing = { workspace = true }
smol_str = { workspace = true }
dashmap = { workspace = true }
ropey = { workspace = true }